### ISSUE TITLE
Wrong data in Gin log

### ISSUE THREAD

**Issue by vadimyer** [olahol/melody#10]
Hello!

This is a bit cosmetic, but when trying out the basic example I've found that when you close the page (the ws connection) Gin is giving a log message with 200 code routing to /ws, with the amount of time the connection was alive. You can try it out. Is this intended or can be fixed?

It actually also gives a 304 for a root route: https://s.vadimyer.com/1632849b-d353-4882-bee1-72bf006e645c.png

**Comment by olahol** [comment]
Interesting, my first intuition is that this is due to Gin's default logger not having any special logging capabilities for websockets. 

Thank you for bringing this up, I will take a look at it later today.

**Comment by olahol** [comment]
I've looked into this and I think this is due to the way the default gin logger works that it only prints request after they are processed:

https://github.com/gin-gonic/gin/blob/develop/logger.go#L63

So to get correct logging messages the default gin logger will have to be modified with some code to check if the request was upgraded to a websocket connection.

The 304 on root is default behavior of GIN when the page hasn't been modified.

Thanks for your input.

**Comment by vadimyer** [comment]
Thanks for the reply.
Can you please explain how would I use this framework with Echo framework? Since the latter doesn't have a c.Writer, but c.Response(), which gives a weird error ._.

**Comment by olahol** [comment]
Echo is little bit special in that they don't by default implement `http.ResponseWriter` and `*http.Request` you have to cast some stuff to get them, here is the basic chat example using Echo framework:

```go
package main

import (
	"github.com/labstack/echo"
	"github.com/labstack/echo/engine/standard"
	"github.com/labstack/echo/middleware"
	"github.com/olahol/melody"
	"net/http"
)

func main() {
	e := echo.New()
	m := melody.New()

	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	e.GET("/", func(c echo.Context) error {
		http.ServeFile(c.Response().(*standard.Response).ResponseWriter, c.Request().(*standard.Request).Request, "index.html")
		return nil
	})

	e.GET("/ws", func(c echo.Context) error {
		m.HandleRequest(c.Response().(*standard.Response).ResponseWriter, c.Request().(*standard.Request).Request)
		return nil
	})

	m.HandleMessage(func(s *melody.Session, msg []byte) {
		m.Broadcast(msg)
	})

	e.Run(standard.New(":5000"))
}
```

**Comment by vadimyer** [comment]
Thanks!
