### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by gg2001** [olahol/melody#13]
Hi, I run a melody server on EC2 which uses websockets and I was wondering how I would add SSL support. Is it the same way you would SSL like in a golang http server like so:

http.ListenAndServeTLS(":8081", "cert.pem", "key.pem", nil)

Or do you use something different?

**Comment by jontonsoup** [comment]
@gg2001 did you figure this out? `wss` doesn't work /cc @olahol

**Comment by gg2001** [comment]
No I didn't. I did not use SSL.
