### ISSUE TITLE
json render

### ISSUE THREAD

**Issue by onerciller** [olahol/melody#17]
hello, How I can return as json instead of servefile. I want to get as json to socket and I will make client with js completely. do you have any example about this?

**Comment by olahol** [comment]
I don't I understand the question, `http.ServeFile` is part of go's standard library.

**Comment by onerciller** [comment]
I know it but i want to return as json to data instead of servefile how can
i do this could i explain it?

23 Oca 2017 17:27 tarihinde "Ola Holmström" <notifications@github.com>
yazdı:
