### ISSUE TITLE
No need Mutex if you use Channel. Am I right?

### ISSUE THREAD

**Issue by happierall** [olahol/melody#20]
I'm talk about https://github.com/olahol/melody/blob/master/hub.go#L34-L36 and code below

**Comment by happierall** [comment]
Access tot hub.session already synchronous, because channels not buffered.

https://blog.golang.org/share-memory-by-communicating

**Comment by happierall** [comment]
It's code totally synchronous...
https://github.com/olahol/melody/blob/master/examples/gophers/main.go

**Comment by olahol** [comment]
It's locked because it can be accessed asynchronously by `hub.len()`.

https://github.com/olahol/melody/blob/master/hub.go#L71-L76

**Comment by happierall** [comment]
Understand, thank you
