### ISSUE TITLE
Is the hub mutex really needed?

### ISSUE THREAD

**Issue by elimist** [olahol/melody#22]
Hey, thanks for making this library, it's great!

I was wondering: is the mutex [here](https://github.com/olahol/melody/blob/master/hub.go#L29) really necessary? It seems the sessions map will never be written to by more than one goroutine and there would probably be some perf gains by removing the lock.

**Comment by olahol** [comment]
It wasn't needed before the `hub.len()` method which can read `sessions` asynchronously. It is probably possible to rewrite it without using locks though.

I answered this before:

https://github.com/olahol/melody/issues/20

**Comment by elimist** [comment]
Sorry, I missed that issue. That clears it up, thanks!
