### ISSUE TITLE
403 error with localhost

### ISSUE THREAD

**Issue by happierall** [olahol/melody#23]
Please add this:

    var upgrader = websocket.Upgrader{
        CheckOrigin: func(r *http.Request) bool { return true },
    }

[Source](https://godoc.org/github.com/gorilla/websocket#hdr-Origin_Considerations)

**Comment by happierall** [comment]
Yes, I can do this:
	
    mrouter.Upgrader.CheckOrigin = func(r *http.Request) bool {return true}

But by default will be better.

**Comment by olahol** [comment]
This is now the default. Thanks @happierall.
