### ISSUE TITLE
Tagging a release as v1

### ISSUE THREAD

**Issue by robbiet480** [olahol/melody#29]
With my recent changes (even before them honestly) I think melody is at a good spot for a tagging a v1 release, which would allow users to use `gopkg.in` to do stable imports of the package. What do you think @olahol?

**Comment by olahol** [comment]
Yes, this is a good idea I hadn't thought about it before, thank you for bringing it to my attention. I will tag HEAD as `v1` in a moment.

**Comment by olahol** [comment]
Okay, now there is a `v1` tag https://github.com/olahol/melody/releases.

**Comment by robbiet480** [comment]
@olahol You may want to update the README.md to suggest users use that instead of the Github link if they want stability...

**Comment by robbiet480** [comment]
`gopkg.in/olahol/melody.v1`

**Comment by olahol** [comment]
Done, I have updated the README and examples/ with the `gopkg.in` import.
