### ISSUE TITLE
Ability to close hub

### ISSUE THREAD

**Issue by saulshanabrook** [olahol/melody#3]
It [looks like](https://github.com/olahol/melody/blob/391be842a938ca24ed8253d9ab45fe78f8bf8ab3/hub.go#L19-L42) once you start a melody server, that `hub.run()` goroutine will continue forever. This usually makes sense, but in my tests I often want to start up a hub, through some websocket connections at it, then tair it down at the end of the test.

What do you think about adding the ability to call `Run` with some sort of cancellation? Maybe either a [context](https://godoc.org/golang.org/x/net/context) or just a `chan struct{}` that you would close to stop the run?

**Comment by olahol** [comment]
You right, it's probably a good idea to have some sort of tear down function to clean up loose goroutines, I implemented something `757ee23`, check and see if this will suit your needs.

**Comment by saulshanabrook** [comment]
@olahol Looks great. Do you think it would make sense to close the output channel on all sessions and close all connections as well? Like [run this code](https://github.com/olahol/melody/blob/757ee23f879ea4ff1a2a225269105945f397e2f4/hub.go#L29-L30) for each session on close?

**Comment by olahol** [comment]
Yes, I added a snippet that closes all current sessions 50189eecc19d791bf08352e871d5c1eb74b20134, although I will have to investigate more to see if this actually cleans up all possible running goroutines.

**Comment by saulshanabrook** [comment]
Awesome, thank you so much. I [wrote a post](http://www.saulshanabrook.com/testing-for-zombie-goroutines/) about testing for zombie goroutines. It is a bit messy sometimes, because I had to do a `time.Sleep(time.Millisecond)` in my tests so that the goroutine ended, before verifying that it had close.If you figure out a better way, I would love to see it.

**Comment by olahol** [comment]
What a nice blog post :) I'm going to see if I can you some of these techniques when I'm fleshing out the test for the `Stop` method.

**Comment by saulshanabrook** [comment]
I guess you might not need the `time.Sleep` because `Close()` will block until it pulls that value off and returns, right?

**Comment by olahol** [comment]
Yes, but now I'm wondering if I have the order of `close(s.output)` and `s.Close()` wrong.

**Comment by saulshanabrook** [comment]
Hm, dunno.

Do you think it would also make sense to close [all other goroutines started](https://github.com/olahol/melody/blob/5c5e059a072dd16407481e9d09a455f9e5afc561/melody.go#L73-L94)?

**Comment by olahol** [comment]
It's getting late here in Gothenburg, I will have to take a look at this tomorrow, having trouble keeping all the concurrency in my head.

**Comment by saulshanabrook** [comment]
Thanks so much for taking a look at this, no worries

**Comment by olahol** [comment]
I have done some refactoring and now I feel more confident that all sessions and the hub exits.

**Comment by saulshanabrook** [comment]
Looks good to me.

**Comment by olahol** [comment]
Ok I have merged it on the master, I renamed `Stop` to `Close` for naming consistency.
