### ISSUE TITLE
HandleSentMessageBinary func set error

### ISSUE THREAD

**Issue by yangjinecho** [olahol/melody#32]
func (m *Melody) HandleSentMessageBinary(fn func(*Session, []byte)) {
	m.messageSentHandler = fn
}
should be 
func (m *Melody) HandleSentMessageBinary(fn func(*Session, []byte)) {
	m.messageSentHandlerBinary = fn
}

**Comment by olahol** [comment]
Fixed this, thank you @yangjinecho.
