### ISSUE TITLE
Long incoming messages result in connection close

### ISSUE THREAD

**Issue by hryamzik** [olahol/melody#35]
Looks like maximum length is 513 symbols. You can just send any 514 symbol long string to verify.

I serve http with gin-gonic, here's the WS part:
```go
mrouter.HandleMessage(func(s *melody.Session, bytes []byte) {
    log.Printf("WS message: %s\n", bytes)
```

Log message is never printed in case of socket close.

**Comment by olahol** [comment]
Use `m.Config.MaxMessageSize` to allow larger messages.

**Comment by hryamzik** [comment]
@olahol thanks!

```go
mrouter = melody.New()
mrouter.Config.MaxMessageSize = 10240
```

Doesn't seem to work, does this means melody instance should be created in a different way?
