### ISSUE TITLE
When is HandleDisconnect called?

### ISSUE THREAD

**Issue by fiatjaf** [olahol/melody#39]
I couldn't find anywhere in the code a line where `*Melody.disconnectHandler` is called.
That function isn't exported, so it is not being called by another package, right?

**Comment by hugows** [comment]
Isn't it called here?

https://github.com/olahol/melody/blob/7bd65910e5abdd2e7396c23acb13475bff79d1af/melody.go#L200

**Comment by fiatjaf** [comment]
Oops, I was relying on GitHub search and that failed.
Thank you.
