### ISSUE TITLE
Active Management? 

### ISSUE THREAD

**Issue by themartorana** [olahol/melody#53]
There seems to be no active maintenance of this repo, but quite a few active forks. Can we transfer ownership of this repo to someone that is currently working on keeping it current?

Thanks!

**Comment by dalu** [comment]
I've **not** checked all 188 forks at the time of writing.
This one is 10 commits ahead:
https://github.com/gabstv/melody
That one fixes session not being safe for concurrent use and adds a Map function that does something on all sessions. And go mod support is added.

I'm not sure what to do.. here is 1 PR by some chinese guy (#54) who adds some kind of pubsub like feature, but no documentation.

The other PRs here try to fix the concurrency(?) safety of sessions and adding go mod support.

Best bet so far seems to be gabstv's. pubsub feature would be very welcome but without documentation... what's the use?

**Comment by z9905080** [comment]
> I've **not** checked all 188 forks at the time of writing.
> This one is 10 commits ahead:
> https://github.com/gabstv/melody
> That one fixes session not being safe for concurrent use and adds a Map function that does something on all sessions. And go mod support is added.
> 
> I'm not sure what to do.. here is 1 PR by some chinese guy (#54) who adds some kind of pubsub like feature, but no documentation.
> 
> The other PRs here try to fix the concurrency(?) safety of sessions and adding go mod support.
> 
> Best bet so far seems to be gabstv's. pubsub feature would be very welcome but without documentation... what's the use?


Hi, Dalu, I am Taiwanese, not Chinese 
About my fork branch,
I just want to use it for my job

This fork project docs will be updated recently

If you have any questions, you can leave a message directly to me

**Comment by olahol** [comment]
Sorry for not actively maintaining the repo for a long period, will be doing it from now on.
