### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by siredwin** [olahol/melody#58]
@olahol , or anyone. Did you reach the end of the scope of this project?

**Comment by dalu** [comment]
there has been no response forever. PRs aren't taken into consideration.
I guess it's safe to say that this is no longer maintained.

**Comment by supertiger1234** [comment]
whats an alternative?

**Comment by snowdream** [comment]
I need know the result too.

**Comment by siredwin** [comment]
The last update was February 2018 on any of his/her projects. It is fair to say that something unusual happened to Olahol in 2018.
