### ISSUE TITLE
Gophers example writing X and Y values

### ISSUE THREAD

**Issue by Unwarped** [olahol/melody#95]
I was studying the examples and looking at the [Gophers demo](https://github.com/olahol/melody/blob/master/examples/gophers/main.go)
I see that it retrieves the player pointer from session storage, and then writes the X and Y values.
Is this thread safe, or would it be best to have some kind of lock? ( Potential race condition )
I know it's just an example, but I'm new to Go and trying to learn best practices.
```
m.HandleMessage(func(s *melody.Session, msg []byte) {
		p := strings.Split(string(msg), " ")
		value, exists := s.Get("info")

		if len(p) != 2 || !exists {
			return
		}

		info := value.(*GopherInfo)
		info.X = p[0] ⚫
		info.Y = p[1] ⚫

		m.BroadcastOthers([]byte("set "+info.ID+" "+info.X+" "+info.Y), s)
	})
```

**Comment by olahol** [comment]
You are right. I've update the Gophers demo to be more straight forward. Thank you.
